name: Deploy website
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/03*.yml'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3