name: Events Demo01
on: 
  push:
    branches: 
        - main
    paths:
        - '.github/workflows/events.yml'  
jobs:
    events-jobs:
        runs-on: ubuntu-latest
        steps:
          - name: Print greeting
            run: echo "Hello World!"
          - name: Output event data
            run: echo "${{ toJSON(github.event) }}"